
export default function Home() {
  return (
    <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-blue-50 to-indigo-100">
      <main className="text-center px-8">
        <h1 className="text-5xl font-bold text-gray-900 mb-4">
          Welcome to Your Next.js App
        </h1>
        <p className="text-xl text-gray-600 mb-8">
          Built with Next.js 14, TypeScript, and Tailwind CSS
        </p>
        <p className="text-sm text-gray-500">
          Generated by Mindous.ai
        </p>
      </main>
    </div>
  );
}
